# Generated by Django 3.2.3 on 2021-06-04 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CloudAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='名称')),
                ('type', models.CharField(max_length=128, verbose_name='类型')),
                ('status', models.BooleanField(default=True, verbose_name='状态')),
                ('secret', models.CharField(max_length=128, verbose_name='accessSecret')),
                ('key', models.CharField(max_length=128, verbose_name='accessKeyID')),
                ('remarks', models.CharField(max_length=1024, verbose_name='备注')),
            ],
            options={
                'db_table': 'cmdb_cloud_account',
            },
        ),
        migrations.CreateModel(
            name='CloudDiscovery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='名称')),
                ('model', models.IntegerField(verbose_name='绑定模型')),
                ('could_account', models.IntegerField(verbose_name='云账号')),
                ('region', models.JSONField(verbose_name='区域')),
                ('status', models.BooleanField(verbose_name='状态')),
                ('last_sync_status', models.BooleanField(verbose_name='最近同步状态')),
                ('last_sync_time', models.DateTimeField(verbose_name='最近同步时间')),
                ('remarks', models.CharField(max_length=1024, verbose_name='备注')),
            ],
            options={
                'db_table': 'cmdb_cloud_discovery',
            },
        ),
        migrations.CreateModel(
            name='Fields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='名称')),
                ('type', models.CharField(max_length=128, verbose_name='类型')),
                ('is_unique', models.BooleanField(default=False, verbose_name='是否唯一')),
                ('required', models.BooleanField(default=False, verbose_name='是否必填')),
                ('prompt', models.CharField(max_length=256, verbose_name='用户提示')),
                ('group', models.IntegerField(verbose_name='分组')),
                ('model', models.IntegerField(verbose_name='模型')),
                ('is_list', models.BooleanField(default=True, verbose_name='是否列表展示')),
                ('sort', models.SmallIntegerField(verbose_name='顺序')),
                ('default', models.CharField(max_length=256, verbose_name='默认值')),
                ('configuration', models.JSONField(verbose_name='字段不同类型的配置数据')),
            ],
            options={
                'db_table': 'cmdb_model_fields',
            },
        ),
        migrations.CreateModel(
            name='ModelGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='名称')),
                ('type', models.SmallIntegerField(verbose_name='类型')),
                ('remarks', models.CharField(max_length=1024, verbose_name='描述')),
            ],
            options={
                'db_table': 'cmdb_model_group',
            },
        ),
        migrations.CreateModel(
            name='ModelInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='名称')),
                ('icon', models.CharField(max_length=45, verbose_name='图标')),
                ('tag', models.JSONField(verbose_name='标签')),
                ('group', models.IntegerField(verbose_name='所属分组')),
            ],
            options={
                'db_table': 'cmdb_model',
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=128, verbose_name='模型')),
                ('data', models.JSONField(verbose_name='模型')),
            ],
            options={
                'db_table': 'cmdb_resource',
            },
        ),
        migrations.CreateModel(
            name='ResourceRelated',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.IntegerField(verbose_name='源数据ID')),
                ('target', models.IntegerField(verbose_name='源数据ID')),
            ],
            options={
                'db_table': 'cmdb_resource_related',
            },
        ),
    ]
