# Generated by Django 3.2.3 on 2021-05-31 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_auto_20210531_0428'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=45, verbose_name='标题')),
                ('name', models.CharField(default='', max_length=45, verbose_name='名称')),
                ('icon', models.CharField(default='', max_length=45, verbose_name='图标')),
                ('sort', models.IntegerField(default=0, verbose_name='展示顺序')),
                ('parent', models.IntegerField(default=0, verbose_name='父级')),
                ('type', models.IntegerField(default=1, verbose_name='权限类型')),
                ('component', models.CharField(default='', max_length=256, verbose_name='组件地址')),
                ('alias', models.CharField(default='', max_length=256, verbose_name='别名')),
                ('path', models.CharField(default='', max_length=256, verbose_name='路由地址')),
                ('hidden', models.BooleanField(default=False, verbose_name='是否隐藏')),
                ('external_link', models.BooleanField(default=False, verbose_name='是否外链')),
                ('permission', models.CharField(default='', max_length=128, verbose_name='权限标识')),
                ('cache', models.BooleanField(default=False, verbose_name='是否缓存')),
                ('redirect', models.CharField(default='', max_length=256, verbose_name='跳转地址')),
            ],
            options={
                'db_table': 'system_permissions',
            },
        ),
        migrations.CreateModel(
            name='RolePermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.IntegerField(verbose_name='角色ID')),
                ('permission', models.IntegerField(verbose_name='权限ID')),
            ],
            options={
                'db_table': 'system_role_permissions',
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=45, verbose_name='名称')),
                ('remarks', models.CharField(default='', max_length=1024, verbose_name='描述')),
            ],
            options={
                'db_table': 'system_roles',
            },
        ),
        migrations.CreateModel(
            name='UserRoles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField(verbose_name='用户ID')),
                ('role', models.IntegerField(verbose_name='角色ID')),
            ],
            options={
                'db_table': 'system_user_roles',
            },
        ),
    ]
