# Generated by Django 3.2.3 on 2021-06-04 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_permissions_rolepermissions_roles_userroles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissions',
            name='alias',
            field=models.CharField(blank=True, max_length=256, verbose_name='别名'),
        ),
        migrations.AlterField(
            model_name='permissions',
            name='component',
            field=models.CharField(blank=True, max_length=256, verbose_name='组件地址'),
        ),
        migrations.AlterField(
            model_name='permissions',
            name='icon',
            field=models.CharField(blank=True, max_length=45, verbose_name='图标'),
        ),
        migrations.AlterField(
            model_name='permissions',
            name='name',
            field=models.CharField(blank=True, max_length=45, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='permissions',
            name='path',
            field=models.CharField(blank=True, max_length=256, verbose_name='路由地址'),
        ),
        migrations.AlterField(
            model_name='permissions',
            name='permission',
            field=models.CharField(blank=True, max_length=128, verbose_name='权限标识'),
        ),
        migrations.AlterField(
            model_name='permissions',
            name='redirect',
            field=models.CharField(blank=True, max_length=256, verbose_name='跳转地址'),
        ),
        migrations.AlterField(
            model_name='permissions',
            name='title',
            field=models.CharField(blank=True, max_length=45, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='roles',
            name='remarks',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='描述'),
        ),
    ]
