# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-11-18 02:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cloud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='云厂商名称', max_length=50, verbose_name='云厂商名称')),
                ('code', models.CharField(help_text='云厂商编号', max_length=50, verbose_name='云厂商编号')),
            ],
        ),
        migrations.CreateModel(
            name='IP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(db_index=True, help_text='ip地址', verbose_name='IP')),
            ],
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instanceID', models.CharField(db_index=True, help_text='实例ID', max_length=50, verbose_name='实例ID')),
                ('instanceType', models.CharField(help_text='实例类型', max_length=50, verbose_name='实例类型')),
                ('cpu', models.CharField(db_index=True, help_text='实例CPU', max_length=50, verbose_name='CPU')),
                ('memory', models.CharField(help_text='实例内存', max_length=50, verbose_name='memory')),
                ('instanceName', models.CharField(db_index=True, help_text='实例名称', max_length=50, verbose_name='实例名称')),
                ('createdTime', models.DateTimeField(db_index=True, help_text='创建时间', verbose_name='创建时间')),
                ('expiredTime', models.DateTimeField(db_index=True, help_text='到期时间', verbose_name='到期时间')),
                ('cloud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.Cloud')),
            ],
        ),
        migrations.AddField(
            model_name='ip',
            name='inner',
            field=models.ForeignKey(help_text='内网IP', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='innerIP', to='resources.Server'),
        ),
        migrations.AddField(
            model_name='ip',
            name='public',
            field=models.ForeignKey(help_text='外网IP', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='publicIP', to='resources.Server'),
        ),
    ]
