---                                                                                                                                                                            
- hosts: all 
  become_user: root
  gather_facts: no
  tasks:
  - name: touch api.txt
    file: path=/tmp/test.txt state=touch  mode=0777
  
  - name: touch api.txt
    file: path=/tmp/test.txt state=touchs  mode=0777
